### ISSUE TITLE
training and evaluation errors

### ISSUE THREAD

**Issue by songw-zju** [dante0shy/SpSequenceNet#1]
Hi, thanks for your great work!
I'm getting errors when trying to run the code unet.py/val_unet.py.
when I run val_unet.py with the provided pretrain model net-000000032.pth, the result is 0:
```
classes          IoU
----------------------------
unlabeled     : 0.000   (     0/476757723)
car           : 0.000   (     0/29898289)
bicycle       : 0.000   (     0/247796)
motorcycle    : 0.000   (     0/345868)
truck         : 0.000   (     0/508704)
other-vehicle : 0.000   (     0/2219728)
person        : 0.000   (     0/79447 )
bicyclist     : 0.000   (     0/594   )
motorcyclist  : 0.000   (     0/22737 )
road          : 0.000   (     0/87963626)
parking       : 0.000   (     0/5947692)
sidewalk      : 0.000   (     0/60280496)
other-ground  : 0.000   (     0/457650)
building      : 0.000   (     0/56878900)
fence         : 0.000   (     0/12642657)
vegetation    : 0.000   (     0/145937016)
trunk         : 0.000   (     0/5503279)
terrain       : 0.000   (     0/64111254)
pole          : 0.000   (     0/1666427)
traffic-sign  : 0.000   (     0/381442)
moving-car    : 0.000   (     0/957816)
moving-bicyclist: 0.000   (     0/306266)
moving-person : 0.000   (     0/397499)
moving-motorcyclist: 0.000   (     0/0     )
moving-other-vehicle: 0.000   (     0/2540  )
moving-truck  : 0.000   (     0/0     )
mean IOU 0.0
```

when I run unet.py, there is error with val step : 0
```
Restore from /home/ws/project/point_cloud/SpSequenceNet/train/semanticKITTI/snap/unetv2_scale20_m16_v2/net-000000000.pth
#classifer parameters 6663642
val step : 0
Traceback (most recent call last):
  File "/home/ws/project/point_cloud/SpSequenceNet/train/semanticKITTI/unet.py", line 134, in <module>
    evealer.addBatch(predictions.max(1)[1].cpu().numpy(), batch['y'].cpu().numpy())  # TLabel
  File "/home/ws/project/point_cloud/SpSequenceNet/SpSNet/utils/np_ioueval.py", line 38, in addBatch
    idxs = tuple(np.stack((x_row, y_row), axis=0))
  File "<__array_function__ internals>", line 6, in stack
  File "/home/ws/anaconda3/envs/open3d/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```
I just modify the config.yaml for the dateset. Thanks in advance.

**Comment by dante0shy** [comment]
Sorry for taking so long, I've fixed the bug in the unet,py. 

For the val_unet.py, can you provide more details? Because I can't refactor the problem.

**Comment by songw-zju** [comment]
Thanks for your reply. For the val_unet.py, I just evaluated the trained model you provided.
